use_default_settings: true

general:
  debug: false
  instance_name: "LeadHunter Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"

ui:
  static_use_hash: true
